# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'SideDishApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Toaster', :git => 'https://github.com/devxoul/Toaster.git', :branch => 'master'
  pod 'Alamofire', '~> 5.1'

  # Pods for SideDishApp

end
